### 入力層データの説明

```
python train.py -l 0.001 -D 0.3 -E 1000 -g 0 -B 256 -v 2 -d cbidata -T keys/keys_select -t keys/keys_2018
```
のcachingを一度終えてから^Cで止める。/tmp/moldataの中に入力層のデータが出来上がっている。

In [89]:
import numpy as np
import pickle
from rdkit import Chem

class WidePrint:
    def __enter__(self):
        np.set_printoptions(edgeitems=1000000, linewidth=120)
    def __exit__(self, exc_type, exc_value, traceback):
        np.set_printoptions(edgeitems=3)

In [90]:
ls /tmp/moldata

1mwt.pkl  3cj2.pkl  3m89.pkl  3wzn.pkl  4fcq.pkl  4mq6.pkl  4uyf.pkl  5cyv.pkl
2jgs.pkl  3cj4.pkl  3m8u.pkl  3wzp.pkl  4fcr.pkl  4mr4.pkl  4v01.pkl  5czm.pkl
2oz2.pkl  3cj5.pkl  3m94.pkl  3wzq.pkl  4ffs.pkl  4mr6.pkl  4v04.pkl  5d0c.pkl
2p3i.pkl  3cow.pkl  3m96.pkl  3zcw.pkl  4fht.pkl  4mre.pkl  4w52.pkl  5d0r.pkl
2p7a.pkl  3coy.pkl  3mam.pkl  3zhx.pkl  4fl1.pkl  4mrf.pkl  4w53.pkl  5d1r.pkl
2p7g.pkl  3coz.pkl  3mf5.pkl  3zhz.pkl  4fl2.pkl  4mrg.pkl  4w54.pkl  5d21.pkl
2pqb.pkl  3cr4.pkl  3mhi.pkl  3zi0.pkl  4fl3.pkl  4mrh.pkl  4w55.pkl  5d24.pkl
2pqc.pkl  3cr5.pkl  3mhl.pkl  3zk6.pkl  4flp.pkl  4mue.pkl  4w57.pkl  5d25.pkl
2pym.pkl  3ctr.pkl  3mhm.pkl  3zll.pkl  4fm7.pkl  4mul.pkl  4w9c.pkl  5d26.pkl
2pyn.pkl  3cwk.pkl  3mho.pkl  3zln.pkl  4fm8.pkl  4muv.pkl  4w9d.pkl  5d3c.pkl
2q2n.pkl  3cyz.pkl  3miy.pkl  3zlr.pkl  4fmu.pkl  4my6.pkl  4w9f.pkl  5d3h.pkl
2q63.pkl  3cz1.pkl  3mo2.pkl  3zm9.pkl  4fnn.pkl  4n07.pkl  4w9h.pkl  5d3j.pkl
2q88.pkl  3d0b.pkl  3mo5.pkl  3zos.pkl  4fqo.pkl  4n

In [91]:
data = pickle.load(open('/tmp/moldata/1mwt.pkl', 'rb'))
data

{'H': array([[0, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 'A1': array([[0.]]),
 'A2': array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]]),
 'Y': 1.88,
 'V': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0]),
 'key': '1mwt'}

In [92]:
with WidePrint():
    print(data['V'])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [93]:
with WidePrint():
    print(data['H'])

[[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0

In [94]:
data

{'H': array([[0, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 'A1': array([[0.]]),
 'A2': array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]]),
 'Y': 1.88,
 'V': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0]),
 'key': '1mwt'}

<img src="lig_pocket.png" width="400" />

<img src="lig_pocket_closer.png" width="400" />

### 分子のペアを読み込む

In [95]:
ligand = Chem.MolFromMolFile('cbidata/1mwt/PNM.sdf')

In [96]:
pocket = Chem.MolFromPDBFile('cbidata/1mwt/1mwt_pocket.pdb')

#### コードは0-スタート、上の表示は1-スタートなので、上の表示からは1減らしてアクセス

In [97]:
atom = ligand.GetAtomWithIdx(15)
print(atom.GetIdx(), atom.GetSymbol())

15 O


In [98]:
atom = pocket.GetAtomWithIdx(33)
print(atom.GetIdx(), atom.GetSymbol())

33 C


#### リガンドは最大60の固定枠で格納されているので、ポケットにアクセスする場合はオフセットを指定

In [99]:
with WidePrint():
    print(data['V'])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [100]:
LIGAND_NATOMS = data['V'].sum()

In [101]:
with WidePrint():
    print(data['H'])

[[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0

#### ligand side

In [102]:
with WidePrint():
    print(data['H'][15])

[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### pocket side

In [103]:
with WidePrint():
    print(data['H'][LIGAND_NATOMS+33][21:])

[1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
