## 入力層データの説明

### dataset2.py用

```
python train.py -l 0.001 -D 0.3 -E 1000 -g 0 -B 256 -v 2 -d cbidata -T keys/keys_select -t keys/keys_2018
```
のcachingを一度終えてから^Cで止める。/tmp/moldataの中に入力層のデータが出来上がっている。

In [22]:
import numpy as np
import pickle
from rdkit import Chem

class WidePrint:
    def __enter__(self):
        np.set_printoptions(edgeitems=1000000, linewidth=120)
    def __exit__(self, exc_type, exc_value, traceback):
        np.set_printoptions(edgeitems=3)

In [23]:
ls /tmp/moldata

1mwt.pkl  2pyn.pkl  2qry.pkl  2v58.pkl  2vpo.pkl  2vzr.pkl  2wc4.pkl  2wic.pkl
2jgs.pkl  2q2n.pkl  2qtn.pkl  2v59.pkl  2vrj.pkl  2w08.pkl  2we3.pkl  2wji.pkl
2oz2.pkl  2q63.pkl  2r75.pkl  2vc9.pkl  2vuk.pkl  2w4x.pkl  2weg.pkl
2p3i.pkl  2q88.pkl  2rcb.pkl  2vcb.pkl  2vvn.pkl  2w87.pkl  2weh.pkl
2p7a.pkl  2q89.pkl  2reg.pkl  2vk2.pkl  2vw5.pkl  2w8j.pkl  2wej.pkl
2p7g.pkl  2qbu.pkl  2rin.pkl  2vmd.pkl  2vwc.pkl  2w8w.pkl  2weo.pkl
2pqb.pkl  2qfo.pkl  2uyw.pkl  2vmf.pkl  2vx9.pkl  2w92.pkl  2weq.pkl
2pqc.pkl  2qhm.pkl  2uzj.pkl  2vo4.pkl  2vxn.pkl  2w97.pkl  2wer.pkl
2pym.pkl  2qpu.pkl  2v57.pkl  2vpn.pkl  2vyt.pkl  2w9h.pkl  2wf5.pkl


In [24]:
data = pickle.load(open('/tmp/moldata/1mwt.pkl', 'rb'))
data

{'H': array([[0, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 'A1': array([[1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.]]),
 'A2': array([[ 1.        ,  1.        ,  1.        , ...,  9.66158879, 10.2164881 ,  7.17477031],
        [ 1.        ,  1.        ,  1.        , ..., 10.16116534, 10.74210938,  7.67263749],
        [ 1.        ,  1.        ,  1.        , ...,  8.78645992,  9.47512749,  6.44944501],
        ...,
        [ 9.66158879, 10.16116534,  8.78645992, ...,  1.        ,  1.        ,  1.        ],
        [10.2164881 , 10.74210938,  9.47512749, ...,  1.        ,  1.        ,  1.        ],
        [ 7.17477031,  7.67263749,  6.44944

In [25]:
with WidePrint():
    print(data['V'])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [26]:
with WidePrint():
    print(data['H'])

[[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0

In [27]:
data

{'H': array([[0, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 'A1': array([[1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.]]),
 'A2': array([[ 1.        ,  1.        ,  1.        , ...,  9.66158879, 10.2164881 ,  7.17477031],
        [ 1.        ,  1.        ,  1.        , ..., 10.16116534, 10.74210938,  7.67263749],
        [ 1.        ,  1.        ,  1.        , ...,  8.78645992,  9.47512749,  6.44944501],
        ...,
        [ 9.66158879, 10.16116534,  8.78645992, ...,  1.        ,  1.        ,  1.        ],
        [10.2164881 , 10.74210938,  9.47512749, ...,  1.        ,  1.        ,  1.        ],
        [ 7.17477031,  7.67263749,  6.44944

<img src="lig_pocket.png" width="400" />

<img src="lig_pocket_closer.png" width="400" />

### 分子のペアを読み込む

In [28]:
ligand = Chem.MolFromMolFile('cbidata/1mwt/PNM.sdf')

In [29]:
pocket = Chem.MolFromPDBFile('cbidata/1mwt/1mwt_pocket.pdb')

#### コードは0-スタート、上の表示は1-スタートなので、上の表示からは1減らしてアクセス

In [30]:
atom = ligand.GetAtomWithIdx(15)
print(atom.GetIdx(), atom.GetSymbol())

15 O


In [31]:
atom = pocket.GetAtomWithIdx(33)
print(atom.GetIdx(), atom.GetSymbol())

33 C


#### リガンドは最大60の固定枠で格納されているので、ポケットにアクセスする場合はオフセットを指定

In [32]:
with WidePrint():
    print(data['V'])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [33]:
LIGAND_NATOMS = data['V'].sum()

In [34]:
with WidePrint():
    print(data['H'])

[[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0

#### ligand side

In [35]:
with WidePrint():
    print(data['H'][15])

[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### pocket side

In [36]:
with WidePrint():
    print(data['H'][LIGAND_NATOMS+33][21:])

[1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]


#### intra-ligand

In [37]:
with WidePrint():
    print(data['A2'][15][:LIGAND_NATOMS])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]


#### ligand-pocket

In [38]:
with WidePrint():
    print(data['A2'][15][LIGAND_NATOMS:])

[ 9.16963336  7.7483919   7.55903995  8.31740272  6.85004204  6.97515054  8.4512818   8.89731313  6.41498449
  5.11356373  5.51942796  6.1046805   7.58010145  8.46223079  5.62302356  6.6217244   6.78786815  7.68293733
  7.94130084  8.72762253  8.83286556 10.01719202  9.14277266  8.04116894  7.2209723   6.06976886  7.37576091
  6.7205598   6.1826834   5.92975615  7.22920044  7.83053855  4.80735967  3.43416744  3.51806822  2.59859885
  7.5503196   7.42777039  8.72850142  8.92101788  6.26013634  5.01605124  4.14330653  4.89366591  2.84485588
 11.35404589 10.69273833  9.43395855  8.97541386 10.51744598 10.00621532  9.07606352  8.02942769  7.82496556
  8.85713215  6.67212425  6.76437691  6.04145628  4.86659778  6.5727457   7.58446432  7.10533856  7.38535429
  8.24119979  9.60918509  9.83718827  7.77997558  6.53574816  6.5816795   7.60716465  5.84221028 11.71762182
 10.65147154 11.20869404 12.28043143  9.8568637   9.33652114  9.20739534  9.03493381  9.58168618 12.33860936
 11.17536935 11.529