## 入力層データの説明

### dataset2.py用

```
python train.py -l 0.001 -D 0.3 -E 1000 -g 0 -B 256 -v 2 -d cbidata -T keys/keys_select -t keys/keys_2018
```
のcachingを一度終えてから^Cで止める。/tmp/moldataの中に入力層のデータが出来上がっている。

In [1]:
import numpy as np
import pickle
from rdkit import Chem

class WidePrint:
    def __enter__(self):
        np.set_printoptions(edgeitems=1000000, linewidth=120)
    def __exit__(self, exc_type, exc_value, traceback):
        np.set_printoptions(edgeitems=3)

In [2]:
ls /tmp/moldata

1mwt.pkl  3heg.pkl  3zi0.pkl  4k6i.pkl  4w9i.pkl  5f61.pkl  5myg.pkl  5y8y.pkl
2jgs.pkl  3hjo.pkl  3zk6.pkl  4k7i.pkl  4w9j.pkl  5f62.pkl  5mz8.pkl  5y94.pkl
2oz2.pkl  3hkw.pkl  3zll.pkl  4k7n.pkl  4w9k.pkl  5f63.pkl  5n0f.pkl  5ya5.pkl
2p3i.pkl  3hky.pkl  3zln.pkl  4k7o.pkl  4w9l.pkl  5f8y.pkl  5n16.pkl  5ybi.pkl
2p7a.pkl  3hmo.pkl  3zlr.pkl  4k9y.pkl  4w9w.pkl  5f9b.pkl  5n17.pkl  5yc8.pkl
2p7g.pkl  3hmp.pkl  3zm9.pkl  4kao.pkl  4w9x.pkl  5fa7.pkl  5n18.pkl  5yf1.pkl
2pqb.pkl  3hqr.pkl  3zos.pkl  4kby.pkl  4wet.pkl  5faq.pkl  5n1p.pkl  5yfs.pkl
2pqc.pkl  3hrf.pkl  3zqe.pkl  4kcx.pkl  4wf2.pkl  5fas.pkl  5n1x.pkl  5yft.pkl
2pym.pkl  3hu3.pkl  3zso.pkl  4kfq.pkl  4wf4.pkl  5fb7.pkl  5n1z.pkl  5yh8.pkl
2pyn.pkl  3huc.pkl  3zsq.pkl  4klv.pkl  4whq.pkl  5fbi.pkl  5n21.pkl  5yhe.pkl
2q2n.pkl  3hv7.pkl  3zsx.pkl  4km0.pkl  4whr.pkl  5fck.pkl  5n2t.pkl  5yhg.pkl
2q63.pkl  3hv8.pkl  3zsy.pkl  4km2.pkl  4whs.pkl  5fdz.pkl  5n2x.pkl  5yhl.pkl
2q88.pkl  3hx3.pkl  3zt2.pkl  4kmz.pkl  4wiv.pkl  5f

In [3]:
data = pickle.load(open('/tmp/moldata/1mwt.pkl', 'rb'))
data

{'H': array([[0, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 'A1': array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]]),
 'A2': array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]]),
 'Y': 1.88,
 'V': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,

In [4]:
with WidePrint():
    print(data['V'])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [5]:
with WidePrint():
    print(data['H'])

[[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0

In [6]:
data

{'H': array([[0, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 'A1': array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]]),
 'A2': array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]]),
 'Y': 1.88,
 'V': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

<img src="lig_pocket.png" width="400" />

<img src="lig_pocket_closer.png" width="400" />

### 分子のペアを読み込む

In [7]:
ligand = Chem.MolFromMolFile('cbidata/1mwt/PNM.sdf')

In [8]:
pocket = Chem.MolFromPDBFile('cbidata/1mwt/1mwt_pocket.pdb')

#### コードは0-スタート、上の表示は1-スタートなので、上の表示からは1減らしてアクセス

In [9]:
atom = ligand.GetAtomWithIdx(15)
print(atom.GetIdx(), atom.GetSymbol())

15 O


In [10]:
atom = pocket.GetAtomWithIdx(33)
print(atom.GetIdx(), atom.GetSymbol())

33 C


#### リガンドは最大60の固定枠で格納されているので、ポケットにアクセスする場合はオフセットを指定

In [11]:
with WidePrint():
    print(data['V'])

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [12]:
LIGAND_NATOMS = data['V'].sum()

In [13]:
with WidePrint():
    print(data['H'])

[[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0

#### ligand side

In [14]:
with WidePrint():
    print(data['H'][15])

[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### pocket side

In [15]:
with WidePrint():
    print(data['H'][LIGAND_NATOMS+33][21:])

[1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]


#### intra-ligand

In [16]:
with WidePrint():
    print(data['A2'][15][:LIGAND_NATOMS])

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0]


#### ligand-pocket

In [17]:
with WidePrint():
    print(data['A2'][15][LIGAND_NATOMS:])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
